/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Desktop;
//Below is imported for the URL links to the Youtube Videos.
import java.net.*;

/**
 *
 * @author x14521223
 */
public class BiologySupportVideosGUI extends javax.swing.JFrame {

    /**
     * Creates new form BiologySupportVideos
     */
    public BiologySupportVideosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBtn = new javax.swing.JButton();
        video1Btn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        video2Btn = new javax.swing.JButton();
        video1Lbl = new javax.swing.JLabel();
        video2Lbl = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(null);

        returnBtn.setText("Back to Support");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn);
        returnBtn.setBounds(120, 450, 220, 40);

        video1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/biology video.JPG"))); // NOI18N
        video1Btn.setText("jButton1");
        video1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video1BtnActionPerformed(evt);
            }
        });
        getContentPane().add(video1Btn);
        video1Btn.setBounds(100, 90, 270, 150);

        titleLbl.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        titleLbl.setText("Biology Support Videos");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(19, 29, 463, 55);

        video2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/biologyvideo2.JPG"))); // NOI18N
        video2Btn.setText("jButton1");
        video2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(video2Btn);
        video2Btn.setBounds(100, 270, 270, 140);

        video1Lbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        video1Lbl.setText("Photosynthesis");
        getContentPane().add(video1Lbl);
        video1Lbl.setBounds(150, 240, 170, 20);

        video2Lbl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        video2Lbl.setText("Physical Matter Properties");
        getContentPane().add(video2Lbl);
        video2Lbl.setBounds(120, 420, 220, 22);

        backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        backGround.setText("jLabel2");
        backGround.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 500, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
     SupportProjectGUI mySupportProjectGUI = new SupportProjectGUI();
      mySupportProjectGUI.setVisible(true);
      dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void video1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video1BtnActionPerformed
//This button when pressed brings the user to the YouTube video linked below. I got this code from StackOverflow.     
        try 
        {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=1U36VpCZLuw").toURI());
        }           
        catch (Exception e) {}   // TODO add your handling code here:
    }//GEN-LAST:event_video1BtnActionPerformed

    private void video2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video2BtnActionPerformed
 //This button when pressed brings the user to the YouTube video linked below. I got this code from StackOverflow.
        try 
        {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=cN2YRJCSVVQ").toURI());
        }           
        catch (Exception e) {}  // TODO add your handling code here:
    }//GEN-LAST:event_video2BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiologySupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiologySupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiologySupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiologySupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiologySupportVideosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton video1Btn;
    private javax.swing.JLabel video1Lbl;
    private javax.swing.JButton video2Btn;
    private javax.swing.JLabel video2Lbl;
    // End of variables declaration//GEN-END:variables
}
