/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author x14428778
 */
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class BiologyQuestion1GUI extends javax.swing.JFrame {

    private String questionText1;
    private String answer1;
//private String topic;

    private ArrayList<QuestionCode> aList;

    public BiologyQuestion1GUI() {
        initComponents();
        questionText1 = new String();
        answer1 = new String();
        aList = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        Quiz = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        Biology = new javax.swing.JLabel();
        CtdInfo = new javax.swing.JLabel();
        Question1 = new javax.swing.JLabel();
        AnswerTf = new javax.swing.JTextField();
        ClearText = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        SaveFile = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        BgRound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 550, 0, 0));
        setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quiz.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Quiz.setText("Quiz");
        getContentPane().add(Quiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 80, 60));

        Text.setText("Please answer the following questions");
        getContentPane().add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 330, -1));

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 100, 80));

        Biology.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Biology.setText("Question 1 of 5");
        getContentPane().add(Biology, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 180, 20));

        CtdInfo.setText("Please press add, and then display, to continue with the  Quiz press Next");
        getContentPane().add(CtdInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 440, 20));

        Question1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Question1.setText("Botany is the study of ?");
        getContentPane().add(Question1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 70));

        AnswerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerTfActionPerformed(evt);
            }
        });
        getContentPane().add(AnswerTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 280, -1));

        ClearText.setText("Clear Text");
        ClearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearTextActionPerformed(evt);
            }
        });
        getContentPane().add(ClearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 100, 80));

        Display.setText("Display");
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 100, 80));

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        getContentPane().add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 100, 80));

        SaveFile.setText("Save File");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        getContentPane().add(SaveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, -1));

        loadFile.setText("Load File");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        getContentPane().add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        BgRound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        BgRound.setText("jLabel1");
        getContentPane().add(BgRound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 520, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed

        BiologyQuestion2GUI myBiologyQuestion2 = new BiologyQuestion2GUI();
        myBiologyQuestion2.setVisible(true);
        dispose();
    }//GEN-LAST:event_NextActionPerformed

    private void AnswerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerTfActionPerformed
        // TODO add your handling code here: THIS IS THE GUESS BOX


    }//GEN-LAST:event_AnswerTfActionPerformed

    private void ClearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearTextActionPerformed
        // set text in textfields to " "

        AnswerTf.setText("");

    }//GEN-LAST:event_ClearTextActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        // Loop through arraylist of question objects
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Question: " + aList.get(i).getQuestionText1() + "\n Answer: " + aList.get(i).getAnswer1());
        }
    }//GEN-LAST:event_DisplayActionPerformed


    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        questionText1 = Question1.getText();
        answer1 = AnswerTf.getText();

        //create a new object 
        QuestionCode q = new QuestionCode();

        //add contents of textfields to q
        q.setQuestionText1(questionText1);
        q.setAnswer1(answer1);

        //add q to ArrayList of QuestionCode Objects 
        aList.add(q);
    

    }//GEN-LAST:event_AddActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        // TODO add your handling code here:
        //This allows the user to save anything entered to the text fields by saving it into a file called output.data in the project folder.
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        String questionText1, answer1;

        try {
            outFile = new File("outputQuiz.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "File is written successfully");

            oStream.close();
         //If there is a problem saving the file the below message will be printed out to the user.   
        } catch (IOException e) {
            System.out.println("Error writing to file" + e);

        }
    }//GEN-LAST:event_SaveFileActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        // TODO add your handling code here:
        // This button allows the user to view any information they saved into the file output.data in the project folder.
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
     try{
         inFile = new File("outputQuiz.data");
         fStream = new FileInputStream(inFile);
         oStream = new ObjectInputStream(fStream);
         
         
         ArrayList <QuestionCode> aList;
         aList = (ArrayList<QuestionCode>)oStream.readObject();
         for(QuestionCode x:aList){
         JOptionPane.showMessageDialog(null, "Question: " + x.getQuestionText1()+ "   Answer: " + x.getAnswer1());
         }
         oStream.close();
     }
     catch(IOException e){
         System.out.println(e);
     }
     catch(ClassNotFoundException ex){
         System.out.println(ex);
         
     }   
    }//GEN-LAST:event_loadFileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JTextField AnswerTf;
    private javax.swing.JLabel BgRound;
    private javax.swing.JLabel Biology;
    private javax.swing.JButton ClearText;
    private javax.swing.JLabel CtdInfo;
    private javax.swing.JButton Display;
    private javax.swing.JButton Next;
    private javax.swing.JLabel Question1;
    private javax.swing.JLabel Quiz;
    private javax.swing.JButton SaveFile;
    private javax.swing.JLabel Text;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton loadFile;
    // End of variables declaration//GEN-END:variables
}
