/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import javax.swing.ButtonGroup;
/**
 *
 * @author Shannon
 */
public class BioRevisionGUI extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    
    /**
     * Creates new form PhysicsRevision
     */
    public BioRevisionGUI() {
        initComponents();
        groupButton();
    }
;
    private void groupButton( ) {

ButtonGroup bg1 = new ButtonGroup( );
bg1.add(jRadioButton1);
bg1.add(jRadioButton2);
bg1.add(jRadioButton3);
ButtonGroup bg2 = new ButtonGroup( );
bg2.add(jRadioButton4);
bg2.add(jRadioButton5);
bg2.add(jRadioButton6);
ButtonGroup bg3 = new ButtonGroup( );
bg3.add(jRadioButton7);
bg3.add(jRadioButton8);
bg3.add(jRadioButton9);
ButtonGroup bg4 = new ButtonGroup( );
bg4.add(jRadioButton10);
bg4.add(jRadioButton11);
bg4.add(jRadioButton12);

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        btnRadios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        btnRadios2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        btnRadios3 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        btnRadios4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jRadioButton1.setText("Solid");
        jRadioButton1.setOpaque(false);
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 100, 80, 23);

        jRadioButton2.setText("Liquid");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(130, 100, 60, 23);

        jRadioButton3.setText("Any");
        jRadioButton3.setOpaque(false);
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(230, 100, 90, 23);

        btnRadios.setForeground(new java.awt.Color(255, 255, 255));
        btnRadios.setText("Pick");
        btnRadios.setToolTipText("");
        btnRadios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRadios.setContentAreaFilled(false);
        btnRadios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRadios.setFocusPainted(false);
        btnRadios.setFocusTraversalPolicyProvider(true);
        btnRadios.setRequestFocusEnabled(false);
        btnRadios.setVerifyInputWhenFocusTarget(false);
        btnRadios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadios);
        btnRadios.setBounds(380, 110, 60, 20);

        jLabel1.setText("What form should the food be?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 217, 14);

        jLabel2.setText("The paper must be ________ if fat is present?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 150, 280, 14);

        jRadioButton4.setText("Folded");
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(20, 180, 100, 23);

        jRadioButton5.setText("Transparent");
        jRadioButton5.setOpaque(false);
        getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(140, 180, 100, 23);

        jRadioButton6.setText("Black");
        jRadioButton6.setOpaque(false);
        getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(260, 180, 80, 23);

        btnRadios2.setForeground(new java.awt.Color(255, 255, 255));
        btnRadios2.setText("Pick");
        btnRadios2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRadios2.setContentAreaFilled(false);
        btnRadios2.setVerifyInputWhenFocusTarget(false);
        btnRadios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadios2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadios2);
        btnRadios2.setBounds(380, 180, 60, 21);

        jLabel3.setText("What solution is added first?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(24, 253, 190, 14);

        jRadioButton7.setText("Water");
        jRadioButton7.setOpaque(false);
        getContentPane().add(jRadioButton7);
        jRadioButton7.setBounds(21, 300, 70, 23);

        jRadioButton8.setText("Oil");
        jRadioButton8.setOpaque(false);
        getContentPane().add(jRadioButton8);
        jRadioButton8.setBounds(109, 300, 70, 23);

        jRadioButton9.setText("Juice");
        jRadioButton9.setOpaque(false);
        getContentPane().add(jRadioButton9);
        jRadioButton9.setBounds(201, 300, 80, 23);

        btnRadios3.setForeground(new java.awt.Color(255, 255, 255));
        btnRadios3.setText("Pick");
        btnRadios3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRadios3.setContentAreaFilled(false);
        btnRadios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadios3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadios3);
        btnRadios3.setBounds(380, 300, 60, 21);

        jLabel4.setText("What color will it turn id protien is present?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 360, 220, 14);

        jRadioButton10.setText("Green");
        jRadioButton10.setOpaque(false);
        getContentPane().add(jRadioButton10);
        jRadioButton10.setBounds(21, 391, 80, 23);

        jRadioButton11.setText("Blue");
        jRadioButton11.setOpaque(false);
        getContentPane().add(jRadioButton11);
        jRadioButton11.setBounds(120, 390, 70, 23);

        jRadioButton12.setText("Violet");
        jRadioButton12.setOpaque(false);
        getContentPane().add(jRadioButton12);
        jRadioButton12.setBounds(210, 390, 70, 23);

        btnRadios4.setForeground(new java.awt.Color(255, 255, 255));
        btnRadios4.setText("Pick");
        btnRadios4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRadios4.setContentAreaFilled(false);
        btnRadios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadios4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRadios4);
        btnRadios4.setBounds(380, 380, 60, 21);

        jLabel5.setText("Refresh Your Mind");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(204, 18, 120, 14);

        jToggleButton1.setText("Back to Homepage");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(10, 440, 150, 23);

        jToggleButton2.setText("Refresh");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(330, 440, 150, 23);

        jLabel6.setText("Protien");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 220, 90, 14);

        jLabel7.setText("Fat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 50, 34, 14);

        jButton1.setText("Keep Track Of Your Score!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 480, 260, 23);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Science.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(-10, 0, 510, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRadiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadiosActionPerformed
    String radioTest="";
    if(jRadioButton1.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
    if(jRadioButton2.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
    if(jRadioButton3.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Correct Answer! Very Good!");
    }
// TODO add your handling code here:
    }//GEN-LAST:event_btnRadiosActionPerformed

    private void btnRadios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadios2ActionPerformed
       String radioTest="";
    if(jRadioButton4.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
    if(jRadioButton5.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Cprrect! Well Done!");
    }
if(jRadioButton6.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnRadios2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void btnRadios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadios3ActionPerformed
         String radioTest="";
    if(jRadioButton7.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null,"Correct! Well Done!");
    }
    if(jRadioButton8.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
if(jRadioButton9.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnRadios3ActionPerformed

    private void btnRadios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadios4ActionPerformed
    String radioTest="";
    if(jRadioButton10.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
    if(jRadioButton11.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Incorrect Answer! Try Again!");
    }
if(jRadioButton12.isSelected()){
javax.swing.JOptionPane.showMessageDialog(null, "Correct!");
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnRadios4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
ExperimentsGUI myExperimentsGUI;
  myExperimentsGUI = new ExperimentsGUI();
myExperimentsGUI.setVisible(true); 
dispose();// TODO add your handling code here:       // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
BioRevisionGUI myBioRevision = new BioRevisionGUI();
myBioRevision.setVisible(true); 
dispose();// TODO add your handling code here: // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
QuestionGUI myQuestionGUI = new QuestionGUI();
myQuestionGUI.setVisible(true);
dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioRevisionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BioRevisionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRadios;
    private javax.swing.JButton btnRadios2;
    private javax.swing.JToggleButton btnRadios3;
    private javax.swing.JButton btnRadios4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    private static class Experiments {

        public Experiments() {
        }
    }
}
