/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Gareth
 */
public class ChemistryQuestion3GUI extends javax.swing.JFrame {
    public String chemquestionText3;
    public String chemAnswer3;
    private ArrayList<QuestionCode> aList;

    /**
     * Creates new form ChemistryQuestion3
     */
    public ChemistryQuestion3GUI() {
        initComponents();
        chemquestionText3 = new String();
        chemAnswer3 = new String();
        aList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quiz = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Chemistry = new javax.swing.JLabel();
        Question3 = new javax.swing.JLabel();
        AnswerTf = new javax.swing.JTextField();
        CtdInfo = new javax.swing.JLabel();
        Clear = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        AddBtn = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        SaveFile = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        Bground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quiz.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Quiz.setText("Quiz");
        getContentPane().add(Quiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        Text.setText("Please answer the following Questions");
        getContentPane().add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 270, -1));

        Chemistry.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Chemistry.setText("Question 3 of 5");
        getContentPane().add(Chemistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 167, 110, 20));

        Question3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Question3.setText("True or false? Acids have a pH level below 7.");
        getContentPane().add(Question3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 450, -1));

        AnswerTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnswerTfActionPerformed(evt);
            }
        });
        getContentPane().add(AnswerTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 310, -1));

        CtdInfo.setText("Please press add, and then display, to continue with the  Quiz press Next");
        getContentPane().add(CtdInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 440, 20));

        Clear.setText("Clear");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 100, 80));

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 100, 80));

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 100, 80));

        Display.setText("Display");
        Display.setMaximumSize(new java.awt.Dimension(83, 23));
        Display.setMinimumSize(new java.awt.Dimension(83, 23));
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        getContentPane().add(Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 100, 80));

        SaveFile.setText("Save File");
        SaveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileActionPerformed(evt);
            }
        });
        getContentPane().add(SaveFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        loadFile.setText("Load File");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        getContentPane().add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        Bground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        Bground.setText("jLabel1");
        getContentPane().add(Bground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 570, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnswerTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnswerTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnswerTfActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        //sets text field to blank
        AnswerTf.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        ChemistryQuestion4GUI myChemistryQuestion4 = new ChemistryQuestion4GUI();
        myChemistryQuestion4.setVisible(true);
        dispose();
    }//GEN-LAST:event_NextActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed

        chemquestionText3 = Question3.getText();
        chemAnswer3 = AnswerTf.getText();

        //create a new QuestionCode
        QuestionCode q = new QuestionCode();

        //add Contents of textfields to q
        q.setchemquestionText3(chemquestionText3);
        q.setchemAnswer3(chemAnswer3);

        //add q to arrayList of QuestionCode Objects
        aList.add(q);
    }//GEN-LAST:event_AddBtnActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed

        // Loop through arraylist of question objects
        for(int i = 0; i < aList.size();i++){
            JOptionPane.showMessageDialog(null, "Question: "+aList.get(i).getchemquestionText3()+"\n Answer: "+aList.get(i).getchemAnswer3());
        }
    }//GEN-LAST:event_DisplayActionPerformed

    private void SaveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileActionPerformed
        // TODO add your handling code here:
        //This allows the user to save anything entered to the text fields by saving it into a file called output.data in the project folder.
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        String chemquestionText3, chemAnswer3;

        try {
            outFile = new File("outputQuiz.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "File is written successfully");

            oStream.close();
            //If there is a problem saving the file the below message will be printed out to the user.
        } catch (IOException e) {
            System.out.println("Error writing to file" + e);

        }
    }//GEN-LAST:event_SaveFileActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        // TODO add your handling code here:
        // This button allows the user to view any information they saved into the file output.data in the project folder.
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;

        try{
            inFile = new File("outputQuiz.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);

            ArrayList <QuestionCode> aList;
            aList = (ArrayList<QuestionCode>)oStream.readObject();
            for(QuestionCode x:aList){
                JOptionPane.showMessageDialog(null, "Question: " + x.getchemquestionText3()+ "   Answer: " + x.getchemAnswer3());
            }
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);

        }
    }//GEN-LAST:event_loadFileActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AnswerTf;
    private javax.swing.JLabel Bground;
    private javax.swing.JLabel Chemistry;
    private javax.swing.JButton Clear;
    private javax.swing.JLabel CtdInfo;
    private javax.swing.JButton Display;
    private javax.swing.JButton Next;
    private javax.swing.JLabel Question3;
    private javax.swing.JLabel Quiz;
    private javax.swing.JButton SaveFile;
    private javax.swing.JLabel Text;
    private javax.swing.JButton loadFile;
    // End of variables declaration//GEN-END:variables
}
