/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author alice
 */
public class EnrollFormGUI extends javax.swing.JFrame {

    private String name;
    private String supportClass;
    private String province;
    private int contact;
    //declare arraylist of question objects
    private ArrayList<EnrollForm> aList;

    /**
     * Creates new form EnrollFormGUI
     */
    public EnrollFormGUI() {
        initComponents();
        name = new String();
        supportClass = new String();
        province = new String();
        contact = 0;
        //create arraylist of Question objects
        aList = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        supportClassLbl = new javax.swing.JLabel();
        contactLbl = new javax.swing.JLabel();
        supportClassTf = new javax.swing.JTextField();
        contactTf = new javax.swing.JTextField();
        displayBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        nameTf = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        provinceLbl = new javax.swing.JLabel();
        provinceTf = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        Title.setText("Enrollment Form");
        getContentPane().add(Title);
        Title.setBounds(60, 40, 360, 50);

        nameLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameLbl.setText("Name:");
        getContentPane().add(nameLbl);
        nameLbl.setBounds(40, 150, 130, 30);

        supportClassLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        supportClassLbl.setText("Revision Support Class:");
        getContentPane().add(supportClassLbl);
        supportClassLbl.setBounds(40, 200, 170, 17);

        contactLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        contactLbl.setText("Contact Number:");
        getContentPane().add(contactLbl);
        contactLbl.setBounds(40, 300, 120, 17);

        supportClassTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportClassTfActionPerformed(evt);
            }
        });
        getContentPane().add(supportClassTf);
        supportClassTf.setBounds(220, 190, 200, 30);

        contactTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactTfActionPerformed(evt);
            }
        });
        getContentPane().add(contactTf);
        contactTf.setBounds(220, 290, 200, 30);

        displayBtn.setText("Display All");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn);
        displayBtn.setBounds(200, 383, 100, 40);

        clearBtn.setText("Clear Form");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearBtn);
        clearBtn.setBounds(90, 383, 100, 40);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(400, 383, 80, 40);

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(310, 383, 80, 40);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(10, 383, 70, 40);

        nameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTfActionPerformed(evt);
            }
        });
        getContentPane().add(nameTf);
        nameTf.setBounds(220, 140, 200, 30);

        backBtn.setText("Back to Support");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(320, 440, 160, 60);

        provinceLbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        provinceLbl.setText("Province:");
        getContentPane().add(provinceLbl);
        provinceLbl.setBounds(50, 250, 150, 17);

        provinceTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinceTfActionPerformed(evt);
            }
        });
        getContentPane().add(provinceTf);
        provinceTf.setBounds(220, 240, 200, 30);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(10, 440, 100, 60);

        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBtn);
        viewBtn.setBounds(160, 440, 120, 60);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        backgroundLbl.setText("jLabel1");
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 500, 1100);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Get text from TextFields
        name = nameTf.getText();
        supportClass = supportClassTf.getText();
        province = provinceTf.getText();
        contact = Integer.parseInt(contactTf.getText());

        //create a new Question object
        EnrollForm q = new EnrollForm();

        //add contents of textfields to q
        q.setName(name);
        q.setSupportClass(supportClass);
        q.setProvince(province);
        q.setContact(contact);

        //add q to arrayList of Question objects
        aList.add(q);
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // Loop through arraylist of question objects
        for (int i = 0; i < aList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Name: " + aList.get(i).getName() + "\n SupportClass: " + aList.get(i).getSupportClass() + "\n Province: " + aList.get(i).getProvince() + "\n Contact: " + aList.get(i).getContact());
        }// TODO add your handling code here:
    }//GEN-LAST:event_displayBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // set text in textfields to " "
        nameTf.setText("");
        supportClassTf.setText("");
        provinceTf.setText("");
        contactTf.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        String searchProvince = JOptionPane.showInputDialog(null, "Please enter the province you would like to search for");
        
        for (int i = 0; i < aList.size(); i++) {
            if (searchProvince.equalsIgnoreCase(aList.get(i).getProvince())) {
                JOptionPane.showMessageDialog(null, "Name: " + aList.get(i).getName() + "\n SupportClass: " + aList.get(i).getSupportClass() + "\n Province: " + aList.get(i).getProvince() + "\n Contact: " + aList.get(i).getContact());

            }
        }

// TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
       
        //If nothing is entered into the Textfields the below message will be displayed.    
        if (nameTf.getText().equals("") || supportClassTf.getText().equals("") || provinceTf.getText().equals("") || contactTf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter your name and weighting to delete");
        } 
        //Check if array list is empty
        else if (aList.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Sorry, there are no items to delete at this time");
        } 
        
        else {
            name = nameTf.getText();
            supportClass = supportClassTf.getText();
            province = provinceTf.getText();
            contact = Integer.parseInt(contactTf.getText());
        //Checking if any of the items are the same, if all 4 are, they will be removed from the array list
            for (int i = 0; i < aList.size(); i++) {

                if (aList.get(i).getName().equals(name)
                        && aList.get(i).getSupportClass().equals(supportClass)
                        && aList.get(i).getProvince().equals(province)
                        && aList.get(i).getContact() == contact) {
                    aList.remove(i);
                    JOptionPane.showMessageDialog(null, "Deleted item from index" + i);
        //Once you've found the item & deleted it we no longer need to search for it so we break out of the loop.
                    break;
                }
                
        //Below is the message printed if we can't find what we are searching for in the loop.                
                if (i == aList.size() - 1) {
                    JOptionPane.showMessageDialog(null, "Sorry, that item could not be found");
                }
            }
        }
       // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void supportClassTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportClassTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supportClassTfActionPerformed

    private void contactTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactTfActionPerformed

    private void nameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTfActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    //Return to the SupportProjectGUI Page
        SupportProjectGUI mySupportProjectGUI = new SupportProjectGUI();
        mySupportProjectGUI.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void provinceTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinceTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinceTfActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
       /* name = nameTf.getText();
        supportClass = supportClassTf.getText();
        province = provinceTf.getText();
        contact = Integer.parseInt(contactTf.getText());

        EnrollForm q = new EnrollForm();
        q.setName(name);
        q.setSupportClass(supportClass);
        q.setProvince(province);
        q.setContact(contact);  */

    //This allows the user to save anything entered to the text fields by saving it into a file called output.data in the project folder.
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "File is written successfully");

            oStream.close();
         //If there is a problem saving the file the below message will be printed out to the user.   
        } catch (IOException e) {
            System.out.println("Error writing to file" + e);

        }


    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed

// This button allows the user to view any information they saved into the file output.data in the project folder.
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
     try{
         inFile = new File("output.data");
         fStream = new FileInputStream(inFile);
         oStream = new ObjectInputStream(fStream);
         
         /*EnrollForm x;
         x = (EnrollForm)oStream.readObject();*/
         ArrayList <EnrollForm> xList;
         xList = (ArrayList<EnrollForm>)oStream.readObject();
         for(EnrollForm x:xList){
         JOptionPane.showMessageDialog(null, "Name: " + x.getName()+ "   SupportClass: " + x.getSupportClass()+ "   Province: " + x.getProvince()+ "   Contact: " + x.getContact());
         }
         oStream.close();
     }
     catch(IOException e){
         System.out.println(e);
     }
     catch(ClassNotFoundException ex){
         System.out.println(ex);
         
     }   
    }//GEN-LAST:event_viewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrollFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrollFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrollFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrollFormGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EnrollFormGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel contactLbl;
    private javax.swing.JTextField contactTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTf;
    private javax.swing.JLabel provinceLbl;
    private javax.swing.JTextField provinceTf;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel supportClassLbl;
    private javax.swing.JTextField supportClassTf;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
