/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;



/**
 *
 * @author bdoor
 */
public class ExamPapers1GUI extends javax.swing.JFrame {

    /**
     * Creates new form ExamPapers1
     */
    public ExamPapers1GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        juniorCertBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        leavingCertBtn = new javax.swing.JButton();
        examinationLbl = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(102, 102, 102));
        titleLbl.setText("Exam papers");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(130, 40, 240, 70);

        juniorCertBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        juniorCertBtn.setForeground(new java.awt.Color(0, 153, 204));
        juniorCertBtn.setText("Junior Certificate");
        juniorCertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juniorCertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(juniorCertBtn);
        juniorCertBtn.setBounds(40, 250, 190, 80);

        homeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeBtn.setForeground(new java.awt.Color(0, 153, 204));
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(80, 430, 130, 40);

        leavingCertBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        leavingCertBtn.setForeground(new java.awt.Color(0, 153, 204));
        leavingCertBtn.setText("Leaving Certificate");
        leavingCertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavingCertBtnActionPerformed(evt);
            }
        });
        getContentPane().add(leavingCertBtn);
        leavingCertBtn.setBounds(270, 250, 190, 80);

        examinationLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        examinationLbl.setForeground(new java.awt.Color(102, 102, 102));
        examinationLbl.setText("Choose Examination:");
        getContentPane().add(examinationLbl);
        examinationLbl.setBounds(30, 150, 191, 30);

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 153, 204));
        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(290, 430, 130, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Science.jpg"))); // NOI18N
        backgroundLbl.setText("jLabel1");
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(-330, -40, 830, 630);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void juniorCertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juniorCertBtnActionPerformed
     SectionGUI c = new SectionGUI();
     c.setVisible(true);
     dispose();
    }//GEN-LAST:event_juniorCertBtnActionPerformed

    private void leavingCertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavingCertBtnActionPerformed
     Section2GUI s = new Section2GUI();
     s.setVisible(true);
     dispose();
    }//GEN-LAST:event_leavingCertBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        HomepageGUI h = new HomepageGUI();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
         SearchGUI m = new SearchGUI();
         m.setVisible(true);
         dispose();
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPapers1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPapers1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPapers1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPapers1GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPapers1GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel examinationLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton juniorCertBtn;
    private javax.swing.JButton leavingCertBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
