/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

/**
 *
 * @author x14322491
 */
public class ExperimentsGUI extends javax.swing.JFrame {

    /**
     * Creates new form Experiments
     */
    public ExperimentsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Experiments = new javax.swing.JLabel();
        Biology = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Physics = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Experiments.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Experiments.setText("Experiments!");
        getContentPane().add(Experiments);
        Experiments.setBounds(200, 10, 130, 17);

        Biology.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Biology.setText("Great Biology Experiments");
        getContentPane().add(Biology);
        Biology.setBounds(160, 60, 220, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Great Chemistry Experiments");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 100, 179, 17);

        Physics.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Physics.setText("Great Physics Experiments!");
        getContentPane().add(Physics);
        Physics.setBounds(160, 140, 166, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Biology Experiments");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 250, 150, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Chemistry Experiments");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 250, 150, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Physics Experiments");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 250, 130, 14);

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 440, 100, 23);

        jButton2.setText("Continue");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 440, 100, 23);

        jButton3.setText("Continue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(380, 443, 90, 20);

        jLabel1.setText("Test For Fat");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 340, 90, 14);

        jLabel2.setText("Test For Protien");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 380, 90, 14);

        jLabel3.setText("Oxidation");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 330, 70, 14);

        jLabel5.setText("Ethonol");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 380, 60, 14);

        jLabel9.setText("Tempiture");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 340, 70, 14);

        jLabel10.setText("Oxidation");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 380, 70, 14);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Science.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-20, -10, 530, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
BiologyGUI myBiology = new BiologyGUI();
myBiology.setVisible(true); 
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Physics myPhysics = new Physics();
myPhysics.setVisible(true);    
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
ChemistryGUI myChemistry;
myChemistry = new ChemistryGUI();
myChemistry.setVisible(true);  
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExperimentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExperimentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExperimentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExperimentsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExperimentsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Biology;
    private javax.swing.JLabel Experiments;
    private javax.swing.JLabel Physics;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
