/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Gareth
 */
public class HomepageGUI extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public HomepageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scienceProjectLbl = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        examPapersBtn = new javax.swing.JButton();
        experimentsBtn = new javax.swing.JButton();
        supportBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        examPapersLbl = new javax.swing.JLabel();
        experimentsLbl = new javax.swing.JLabel();
        supportLbl = new javax.swing.JLabel();
        quizLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 550, 0, 0));
        setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(null);

        scienceProjectLbl.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scienceProjectLbl.setText("Science App");
        getContentPane().add(scienceProjectLbl);
        scienceProjectLbl.setBounds(100, 80, 320, 58);

        welcomeLbl.setText("Welcome to our homepage please select an option");
        getContentPane().add(welcomeLbl);
        welcomeLbl.setBounds(110, 140, 330, 14);

        examPapersBtn.setText("Exam Papers");
        examPapersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examPapersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(examPapersBtn);
        examPapersBtn.setBounds(84, 223, 120, 100);

        experimentsBtn.setText("Experiments");
        experimentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                experimentsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(experimentsBtn);
        experimentsBtn.setBounds(303, 223, 120, 100);

        supportBtn.setText("Support");
        supportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supportBtnActionPerformed(evt);
            }
        });
        getContentPane().add(supportBtn);
        supportBtn.setBounds(84, 404, 120, 100);

        quizBtn.setText("Quiz");
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quizBtn);
        quizBtn.setBounds(303, 404, 120, 100);

        examPapersLbl.setText("Click to view exam papers");
        getContentPane().add(examPapersLbl);
        examPapersLbl.setBounds(73, 203, 160, 14);

        experimentsLbl.setText("Click to view Experiments");
        getContentPane().add(experimentsLbl);
        experimentsLbl.setBounds(291, 203, 150, 14);

        supportLbl.setText("Click to view Support");
        getContentPane().add(supportLbl);
        supportLbl.setBounds(84, 384, 120, 14);

        quizLbl.setText("Click to view Quiz");
        getContentPane().add(quizLbl);
        quizLbl.setBounds(312, 384, 110, 14);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        backgroundLbl.setText("jLabel1");
        backgroundLbl.setAutoscrolls(true);
        backgroundLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        backgroundLbl.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 500, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void experimentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_experimentsBtnActionPerformed
        ExperimentsGUI myExperiments = new ExperimentsGUI();
        myExperiments.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_experimentsBtnActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        Quiz1 myQuiz1 = new Quiz1();
        myQuiz1.setVisible(true);
        dispose();
    }//GEN-LAST:event_quizBtnActionPerformed

    private void examPapersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examPapersBtnActionPerformed
      ExamPapers1GUI myExamPapers1GUI = new ExamPapers1GUI();
      myExamPapers1GUI.setVisible(true);
      dispose();
     
    }//GEN-LAST:event_examPapersBtnActionPerformed

    private void supportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supportBtnActionPerformed
            SupportProjectGUI mySupportProjectGUI = new SupportProjectGUI();
            mySupportProjectGUI.setVisible(true);
            dispose();
    }//GEN-LAST:event_supportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomepageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomepageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomepageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomepageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomepageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton examPapersBtn;
    private javax.swing.JLabel examPapersLbl;
    private javax.swing.JButton experimentsBtn;
    private javax.swing.JLabel experimentsLbl;
    private javax.swing.JButton quizBtn;
    private javax.swing.JLabel quizLbl;
    private javax.swing.JLabel scienceProjectLbl;
    private javax.swing.JButton supportBtn;
    private javax.swing.JLabel supportLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
