/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Desktop;
//Below is imported for the URL links to the Youtube Videos.
import java.net.URL;

/**
 *
 * @author x14521223
 */
public class PhysicsSupportVideosGUI extends javax.swing.JFrame {

    /**
     * Creates new form PhysicsSupportVideos
     */
    public PhysicsSupportVideosGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();
        video1Btn = new javax.swing.JButton();
        video2Btn = new javax.swing.JButton();
        videoLbl1 = new javax.swing.JLabel();
        videoLbl2 = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 550));
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        titleLbl.setText("Physics Support Videos");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(10, 20, 469, 56);

        returnBtn.setText("Back to Support");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(returnBtn);
        returnBtn.setBounds(120, 460, 190, 30);

        video1Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/physics video 1.JPG"))); // NOI18N
        video1Btn.setText("jButton1");
        video1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video1BtnActionPerformed(evt);
            }
        });
        getContentPane().add(video1Btn);
        video1Btn.setBounds(110, 90, 220, 160);

        video2Btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/physics video 2.JPG"))); // NOI18N
        video2Btn.setText("jButton2");
        video2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                video2BtnActionPerformed(evt);
            }
        });
        getContentPane().add(video2Btn);
        video2Btn.setBounds(110, 290, 220, 150);

        videoLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        videoLbl1.setText("Physics Proofs");
        getContentPane().add(videoLbl1);
        videoLbl1.setBounds(160, 260, 130, 22);

        videoLbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        videoLbl2.setText("Vectors");
        getContentPane().add(videoLbl2);
        videoLbl2.setBounds(180, 440, 70, 22);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        backgroundLbl.setText("jLabel1");
        backgroundLbl.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 500, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
    SupportProjectGUI mySupportProjectGUI = new SupportProjectGUI();
      mySupportProjectGUI.setVisible(true);
      dispose();    // TODO add your handling code here:
    }//GEN-LAST:event_returnBtnActionPerformed

    private void video1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video1BtnActionPerformed
 //This button when pressed brings the user to the YouTube video linked below. I got this code from StackOverflow.
        try 
        {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=8GHyX0NicgI&list=PLETu0DZChh4Y81hB6u4xKSdgjnfV8wyCe").toURI());
        }           
        catch (Exception e) {}       // TODO add your handling code here:
    }//GEN-LAST:event_video1BtnActionPerformed

    private void video2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_video2BtnActionPerformed
 //This button when pressed brings the user to the YouTube video linked below. I got this code from StackOverflow.   
        try 
        {
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=Uea-F_2uzC8").toURI());
        }           
        catch (Exception e) {}    // TODO add your handling code here:
    }//GEN-LAST:event_video2BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicsSupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicsSupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicsSupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicsSupportVideosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicsSupportVideosGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton returnBtn;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton video1Btn;
    private javax.swing.JButton video2Btn;
    private javax.swing.JLabel videoLbl1;
    private javax.swing.JLabel videoLbl2;
    // End of variables declaration//GEN-END:variables
}
