/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

/**
 *
 * @author x14428778
 */
public class Quiz1 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz1
     */
    public Quiz1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quiz = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        BiologyBtn = new javax.swing.JButton();
        ChemistryBtn = new javax.swing.JButton();
        physicsBtn = new javax.swing.JButton();
        biologyText = new javax.swing.JLabel();
        ChemistryText = new javax.swing.JLabel();
        PhysicsText = new javax.swing.JLabel();
        ReturnBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 550, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Quiz.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Quiz.setText("Quiz");
        getContentPane().add(Quiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 38, -1, -1));

        Text.setText("Please Select a Topic on which you would like to answer Questions on");
        getContentPane().add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 350, 47));

        Text1.setText("there are three topic to choose from");
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        BiologyBtn.setText("BIOLOGY");
        BiologyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiologyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BiologyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 80));

        ChemistryBtn.setText("CHEMISTRY");
        ChemistryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChemistryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ChemistryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 80));

        physicsBtn.setText("PHYSICS");
        physicsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(physicsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 100, 80));

        biologyText.setText("Biology");
        getContentPane().add(biologyText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        ChemistryText.setText("Chemistry");
        getContentPane().add(ChemistryText, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        PhysicsText.setText("Physics");
        getContentPane().add(PhysicsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        ReturnBtn.setText("Return to Homepage");
        ReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ReturnBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 340, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Bg.jpg"))); // NOI18N
        Background.setText("jLabel1");
        Background.setPreferredSize(new java.awt.Dimension(500, 550));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChemistryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChemistryBtnActionPerformed
            ChemistryQuestion1GUI myChemistryQuestion1 = new ChemistryQuestion1GUI();
            myChemistryQuestion1.setVisible(true);
            dispose();
    }//GEN-LAST:event_ChemistryBtnActionPerformed

    private void BiologyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiologyBtnActionPerformed
        BiologyQuestion1GUI myBiologyQuestion1 = new BiologyQuestion1GUI();
        myBiologyQuestion1.setVisible(true);
        dispose();
    }//GEN-LAST:event_BiologyBtnActionPerformed

    private void physicsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsBtnActionPerformed
       PhysicsQuestion1GUI myPhysicsQuestion1GUI = new PhysicsQuestion1GUI();
       myPhysicsQuestion1GUI.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_physicsBtnActionPerformed

    private void ReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBtnActionPerformed
        HomepageGUI myHomepage = new HomepageGUI();
        myHomepage.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReturnBtnActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BiologyBtn;
    private javax.swing.JButton ChemistryBtn;
    private javax.swing.JLabel ChemistryText;
    private javax.swing.JLabel PhysicsText;
    private javax.swing.JLabel Quiz;
    private javax.swing.JButton ReturnBtn;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel biologyText;
    private javax.swing.JButton physicsBtn;
    // End of variables declaration//GEN-END:variables
}
