/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author bdoor
 */
public class SciGUI extends javax.swing.JFrame {

    /**
     * Creates new form Sci
     */
    public SciGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        biologyBtn = new javax.swing.JButton();
        chemistryBtn = new javax.swing.JButton();
        physicsBtn = new javax.swing.JButton();
        subjectLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(102, 102, 102));
        titleLbl.setText("Exam papers");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(130, 50, 240, 47);

        biologyBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        biologyBtn.setForeground(new java.awt.Color(0, 153, 204));
        biologyBtn.setText("Biology");
        biologyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(biologyBtn);
        biologyBtn.setBounds(270, 170, 165, 80);

        chemistryBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chemistryBtn.setForeground(new java.awt.Color(0, 153, 204));
        chemistryBtn.setText("Chemistry");
        chemistryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemistryBtnActionPerformed(evt);
            }
        });
        getContentPane().add(chemistryBtn);
        chemistryBtn.setBounds(40, 260, 165, 80);

        physicsBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        physicsBtn.setForeground(new java.awt.Color(0, 153, 204));
        physicsBtn.setText("Physics");
        physicsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(physicsBtn);
        physicsBtn.setBounds(270, 340, 165, 80);

        subjectLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectLbl.setForeground(new java.awt.Color(102, 102, 102));
        subjectLbl.setText("Choose Subject:");
        getContentPane().add(subjectLbl);
        subjectLbl.setBounds(30, 140, 170, 22);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 153, 204));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(40, 453, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Science.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-350, -10, 980, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void physicsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicsBtnActionPerformed
      PhysicsExamPaperGUI p = new PhysicsExamPaperGUI();
     p.setVisible(true);
     dispose();
    }//GEN-LAST:event_physicsBtnActionPerformed

    private void biologyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologyBtnActionPerformed
      BiologyExamPaperGUI s = new BiologyExamPaperGUI();
     s.setVisible(true);
      dispose();
    }//GEN-LAST:event_biologyBtnActionPerformed

    private void chemistryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemistryBtnActionPerformed
     ChemistryExamPapersGUI c = new ChemistryExamPapersGUI();
     c.setVisible(true);
      dispose();
    }//GEN-LAST:event_chemistryBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        Section2GUI b = new Section2GUI();
        b.setVisible(true);
         dispose();
        
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SciGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SciGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton biologyBtn;
    private javax.swing.JButton chemistryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton physicsBtn;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
