/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bdoor
 */
public class SearchGUI extends javax.swing.JFrame {
        private ArrayList <SearchForm> aList;
        private String examination;
        private String subject;
        private int years;
  
        
    /**
     * Creates new form Search
     */
    public SearchGUI() {
        initComponents();
        //create arraylist of Question objects
        aList = new ArrayList <> ();
        examination = new String();
        subject = new String ();
        years = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        examinationLbl = new javax.swing.JLabel();
        examinationTf = new javax.swing.JTextField();
        subjectLbl = new javax.swing.JLabel();
        subjectTf = new javax.swing.JTextField();
        yearLbl = new javax.swing.JLabel();
        yearsTf = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 550));
        setMinimumSize(new java.awt.Dimension(500, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(102, 102, 102));
        titleLbl.setText("Search");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(179, 11, 122, 70);

        examinationLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        examinationLbl.setForeground(new java.awt.Color(102, 102, 102));
        examinationLbl.setText("Choose Examination:");
        getContentPane().add(examinationLbl);
        examinationLbl.setBounds(10, 115, 191, 30);

        examinationTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examinationTfActionPerformed(evt);
            }
        });
        getContentPane().add(examinationTf);
        examinationTf.setBounds(219, 118, 207, 30);

        subjectLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        subjectLbl.setForeground(new java.awt.Color(102, 102, 102));
        subjectLbl.setText("Choose Subject:");
        getContentPane().add(subjectLbl);
        subjectLbl.setBounds(10, 190, 170, 22);

        subjectTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectTfActionPerformed(evt);
            }
        });
        getContentPane().add(subjectTf);
        subjectTf.setBounds(219, 189, 207, 30);

        yearLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yearLbl.setForeground(new java.awt.Color(102, 102, 102));
        yearLbl.setText("Choose Year:");
        getContentPane().add(yearLbl);
        yearLbl.setBounds(10, 263, 130, 22);

        yearsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearsTfActionPerformed(evt);
            }
        });
        getContentPane().add(yearsTf);
        yearsTf.setBounds(219, 255, 207, 30);

        backBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 153, 204));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(40, 480, 120, 40);

        displayBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(0, 153, 204));
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn);
        displayBtn.setBounds(290, 330, 130, 40);

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(0, 153, 204));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(61, 411, 130, 40);

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(0, 153, 204));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn);
        deleteBtn.setBounds(290, 410, 130, 40);

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(0, 153, 204));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(61, 337, 130, 40);

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 153, 204));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(180, 480, 130, 40);

        viewBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(0, 153, 204));
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        getContentPane().add(viewBtn);
        viewBtn.setBounds(330, 480, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/Science.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-340, -30, 860, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ExamPapers1GUI m = new ExamPapers1GUI();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
       // Loop through arraylist of question objects
        for(int i = 0; i < aList.size();i++){
           JOptionPane.showMessageDialog(null,"examination:  "+aList.get(i).getExamination()+"\n subject: "+aList.get(i).getSubject()+"\n years: "+aList.get(i).getYears());
       }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
       String searchType = JOptionPane.showInputDialog(null, "Please enter the province you would like to search for");
            for (int i = 0; i < aList.size();i++){
                if(searchType.equalsIgnoreCase(aList.get(i).getExamination())){
                    JOptionPane.showMessageDialog(null, "Examination: " +aList.get(i).getExamination()+ "\n Subject: " + aList.get(i).getSubject() + "\n years: " + aList.get(i).getYears());
                }
            }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
            if(examinationTf.getText().equals("")||subjectTf.getText().equals("")||yearsTf.getText().equals("")) {
                  JOptionPane.showMessageDialog(null, "You must enter your name and weighting to delete");
              } 
             //check if array list is empty
              else if (aList.isEmpty()){
                     JOptionPane.showMessageDialog(null, "Sorry, there are no items to delete at this time");
              } 
                  else{
                      examination = examinationTf.getText();
                      subject = subjectTf.getText();
                      years = Integer.parseInt(yearsTf.getText());
                
          //Checking if any of the items are the same, if all 4 are, they will be removed from the array list
            for (int i = 0; i < aList.size(); i++){

                if (aList.get(i).getExamination().equals(examination)&&
                    aList.get(i).getSubject().equals(subject)&&
                    aList.get(i).getYears()== years){
                    aList.remove(i);
                         JOptionPane.showMessageDialog(null, "Deleted item from index" + i);
            break;
        }
        if(i == aList.size() - 1){
            JOptionPane.showMessageDialog(null, "Sorry, that item could not be found");
}
}
}
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // Get text from TextFields
        examination = examinationTf.getText();
        subject = subjectTf.getText();
        years = Integer.parseInt(yearsTf.getText());
        
        //create a new Question object
        SearchForm b = new SearchForm();
        
        b.setExamination(examination);
        b.setSubject(subject);
        b.setYears(years);
        
        //add object to arrayList
        aList.add(b);
        

    }//GEN-LAST:event_addBtnActionPerformed

    private void examinationTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examinationTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_examinationTfActionPerformed

    private void subjectTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectTfActionPerformed

    private void yearsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearsTfActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
    //This allows the user to save anything entered to the text fields by saving it into a file called output.data in the project folder.
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;

        try {
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);

            oStream.writeObject(aList);

            JOptionPane.showMessageDialog(null, "File is written successfully");

            oStream.close();
         //If there is a problem saving the file the below message will be printed out to the user.   
        } catch (IOException e) {
            System.out.println("Error writing to file" + e);

        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // This button allows the user to view any information they saved into the file output.data in the project folder.
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
     try{
         inFile = new File("output.data");
         fStream = new FileInputStream(inFile);
         oStream = new ObjectInputStream(fStream);
         
         /*EnrollForm x;
         x = (EnrollForm)oStream.readObject();*/
         ArrayList <SearchForm> xList;
         xList = (ArrayList<SearchForm>)oStream.readObject();
         for(SearchForm x:xList){
         JOptionPane.showMessageDialog(null, "Examination: " + x.getExamination()+ "   Subject: " + x.getSubject()+ "   Years: " + x.getYears());
         }
         oStream.close();
     }
     catch(IOException e){
         System.out.println(e);
     }
     catch(ClassNotFoundException ex){
         System.out.println(ex);
         
     }   
                                    
    }//GEN-LAST:event_viewBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel examinationLbl;
    private javax.swing.JTextField examinationTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel subjectLbl;
    private javax.swing.JTextField subjectTf;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel yearLbl;
    private javax.swing.JTextField yearsTf;
    // End of variables declaration//GEN-END:variables

    
}
